### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [Rwhytsell/TripTracker#1]
Greetings, I just made a logo for your project, hope you like it.
![tth](https://user-images.githubusercontent.com/35619342/39108136-a9ac6d9a-4694-11e8-9196-1c3c2af72fa6.png)
![ttv](https://user-images.githubusercontent.com/35619342/39108138-aef6685a-4694-11e8-97d6-7477f9a1be65.png)
If you like it, I'll upload the files on a pull request. Please let me know if you want me to modify/add something.

**Comment by Rwhytsell** [comment]
I like the green logo.

If you want you can submit a pull request with it in the resources/drawable.

Just know that this is a pet project and probably won't far.

**Comment by michaelizer** [comment]
Glad you liked it, don't mind that the logo is yours to use it now and in future projects.
[#2}(https://github.com/Rwhytsell/TripTracker/pull/2)
